name: Bug Report
description: Report a bug in the Socialise app. An automated agent will validate and attempt to fix it.
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Please fill out all required fields. An automated agent will pick this up, validate the issue, and attempt a fix.

        **Important:** This form is for reporting bugs in existing behavior only. Feature requests, enhancements, and new functionality should use a different template. Reports that describe desired new behavior will be closed as `not-a-bug`.

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the app is broken?
      options:
        - Frontend - UI/Components
        - Frontend - State Management
        - Backend - API Routes
        - Backend - Database Queries
        - Auth - Login/Register
        - UI/Design - Styling/Layout
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is it?
      options:
        - P1 - Critical (app crashes, data loss, auth broken)
        - P2 - Major (feature broken, wrong data shown)
        - P3 - Minor (visual glitch, edge case, typo)
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps to trigger the bug. Be specific.
      placeholder: |
        1. Log in as ben@demo.com
        2. Navigate to the Explore tab
        3. Click on an event card
        4. Observe the error in the chat section
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What SHOULD happen? Describe the correct existing behavior.
      placeholder: "The chat messages should display with the correct username."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What ACTUALLY happens? Describe the broken behavior you observe.
      placeholder: "The chat messages show 'undefined' instead of the username."
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Affected Component or File (optional)
      description: If you know which file or component is involved, mention it here.
      placeholder: "src/components/EventDetailSheet.jsx"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Attach screenshots or paste error messages if available.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context (optional)
      description: Any other relevant info (browser, device, console errors, etc.)
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following before submitting.
      options:
        - label: This is a bug in existing functionality, NOT a feature request or enhancement.
          required: true
        - label: I have searched existing issues and this bug has not been reported before.
          required: true
