/**
 * Centralised error codes for every API error response.
 *
 * Convention:  ERR_<DOMAIN>_<ACTION>
 *   Domain  = AUTH, EVENT, COMMUNITY, FEED, USER, BUG
 *   Action  = short verb (FETCH, INSERT, UPDATE, DELETE, JOIN, LEAVE, etc.)
 *
 * Every `res.status(4xx|5xx).json(...)` in the route files MUST include
 * a `code` from this module so the frontend always gets a machine-readable
 * identifier alongside the human-readable message.
 */

// ── Auth ───────────────────────────────────────────────────────────────
const AUTH_INVALID_INPUT       = 'ERR_AUTH_INVALID_INPUT';
const AUTH_INVALID_CREDENTIALS = 'ERR_AUTH_INVALID_CREDENTIALS';
const AUTH_DEMO_BLOCKED        = 'ERR_AUTH_DEMO_BLOCKED';
const AUTH_DUPLICATE_EMAIL     = 'ERR_AUTH_DUPLICATE_EMAIL';
const AUTH_CREATE_FAILED       = 'ERR_AUTH_CREATE_FAILED';
const AUTH_TOKEN_MISSING       = 'ERR_AUTH_TOKEN_MISSING';
const AUTH_TOKEN_INVALID       = 'ERR_AUTH_TOKEN_INVALID';
const AUTH_USER_NOT_FOUND      = 'ERR_AUTH_USER_NOT_FOUND';
const AUTH_RATE_LIMITED        = 'ERR_AUTH_RATE_LIMITED';

// ── Events ─────────────────────────────────────────────────────────────
const EVENT_FETCH_FAILED       = 'ERR_EVENT_FETCH_FAILED';
const EVENT_NOT_FOUND          = 'ERR_EVENT_NOT_FOUND';
const EVENT_CREATE_FAILED      = 'ERR_EVENT_CREATE_FAILED';
const EVENT_UPDATE_FAILED      = 'ERR_EVENT_UPDATE_FAILED';
const EVENT_DELETE_FAILED      = 'ERR_EVENT_DELETE_FAILED';
const EVENT_JOIN_FAILED        = 'ERR_EVENT_JOIN_FAILED';
const EVENT_LEAVE_FAILED       = 'ERR_EVENT_LEAVE_FAILED';
const EVENT_SAVE_FAILED        = 'ERR_EVENT_SAVE_FAILED';
const EVENT_UNSAVE_FAILED      = 'ERR_EVENT_UNSAVE_FAILED';
const EVENT_CHAT_FETCH_FAILED  = 'ERR_EVENT_CHAT_FETCH_FAILED';
const EVENT_CHAT_SEND_FAILED   = 'ERR_EVENT_CHAT_SEND_FAILED';
const EVENT_FULL               = 'ERR_EVENT_FULL';
const EVENT_INACTIVE           = 'ERR_EVENT_INACTIVE';
const EVENT_FORBIDDEN          = 'ERR_EVENT_FORBIDDEN';
const EVENT_INVALID_INPUT      = 'ERR_EVENT_INVALID_INPUT';
const EVENT_RECS_FAILED        = 'ERR_EVENT_RECS_FAILED';

// ── Communities ────────────────────────────────────────────────────────
const COMMUNITY_FETCH_FAILED       = 'ERR_COMMUNITY_FETCH_FAILED';
const COMMUNITY_NOT_FOUND          = 'ERR_COMMUNITY_NOT_FOUND';
const COMMUNITY_CREATE_FAILED      = 'ERR_COMMUNITY_CREATE_FAILED';
const COMMUNITY_DUPLICATE_NAME     = 'ERR_COMMUNITY_DUPLICATE_NAME';
const COMMUNITY_JOIN_FAILED        = 'ERR_COMMUNITY_JOIN_FAILED';
const COMMUNITY_LEAVE_FAILED       = 'ERR_COMMUNITY_LEAVE_FAILED';
const COMMUNITY_FOUNDER_LEAVE      = 'ERR_COMMUNITY_FOUNDER_LEAVE';
const COMMUNITY_MEMBERS_FAILED     = 'ERR_COMMUNITY_MEMBERS_FAILED';
const COMMUNITY_CHAT_FETCH_FAILED  = 'ERR_COMMUNITY_CHAT_FETCH_FAILED';
const COMMUNITY_CHAT_SEND_FAILED   = 'ERR_COMMUNITY_CHAT_SEND_FAILED';
const COMMUNITY_INVALID_INPUT      = 'ERR_COMMUNITY_INVALID_INPUT';

// ── Feed ───────────────────────────────────────────────────────────────
const FEED_FETCH_FAILED    = 'ERR_FEED_FETCH_FAILED';
const FEED_CREATE_FAILED   = 'ERR_FEED_CREATE_FAILED';
const FEED_DELETE_FAILED   = 'ERR_FEED_DELETE_FAILED';
const FEED_REACT_FAILED    = 'ERR_FEED_REACT_FAILED';
const FEED_NOT_FOUND       = 'ERR_FEED_NOT_FOUND';
const FEED_FORBIDDEN       = 'ERR_FEED_FORBIDDEN';
const FEED_INVALID_INPUT   = 'ERR_FEED_INVALID_INPUT';

// ── Users ──────────────────────────────────────────────────────────────
const USER_NOT_FOUND           = 'ERR_USER_NOT_FOUND';
const USER_UPDATE_FAILED       = 'ERR_USER_UPDATE_FAILED';
const USER_XP_UPDATE_FAILED    = 'ERR_USER_XP_UPDATE_FAILED';
const USER_DELETE_FAILED       = 'ERR_USER_DELETE_FAILED';
const USER_AVATAR_FAILED       = 'ERR_USER_AVATAR_FAILED';
const USER_INVALID_INPUT       = 'ERR_USER_INVALID_INPUT';
const USER_ROLE_UPDATE_FAILED  = 'ERR_USER_ROLE_UPDATE_FAILED';
const USER_STATS_FAILED        = 'ERR_USER_STATS_FAILED';

// ── Bugs ───────────────────────────────────────────────────────────────
const BUG_INSERT_FAILED    = 'ERR_BUG_INSERT_FAILED';
const BUG_FETCH_FAILED     = 'ERR_BUG_FETCH_FAILED';
const BUG_UPDATE_FAILED    = 'ERR_BUG_UPDATE_FAILED';
const BUG_DELETE_FAILED    = 'ERR_BUG_DELETE_FAILED';
const BUG_NOT_FOUND        = 'ERR_BUG_NOT_FOUND';
const BUG_INVALID_INPUT    = 'ERR_BUG_INVALID_INPUT';

// ── Global / Middleware ────────────────────────────────────────────────
const RATE_LIMITED         = 'ERR_RATE_LIMITED';
const CORS_BLOCKED         = 'ERR_CORS_BLOCKED';

module.exports = {
    // Auth
    AUTH_INVALID_INPUT, AUTH_INVALID_CREDENTIALS, AUTH_DEMO_BLOCKED,
    AUTH_DUPLICATE_EMAIL, AUTH_CREATE_FAILED, AUTH_TOKEN_MISSING,
    AUTH_TOKEN_INVALID, AUTH_USER_NOT_FOUND, AUTH_RATE_LIMITED,
    // Events
    EVENT_FETCH_FAILED, EVENT_NOT_FOUND, EVENT_CREATE_FAILED,
    EVENT_UPDATE_FAILED, EVENT_DELETE_FAILED, EVENT_JOIN_FAILED,
    EVENT_LEAVE_FAILED, EVENT_SAVE_FAILED, EVENT_UNSAVE_FAILED,
    EVENT_CHAT_FETCH_FAILED, EVENT_CHAT_SEND_FAILED, EVENT_FULL,
    EVENT_INACTIVE, EVENT_FORBIDDEN, EVENT_INVALID_INPUT, EVENT_RECS_FAILED,
    // Communities
    COMMUNITY_FETCH_FAILED, COMMUNITY_NOT_FOUND, COMMUNITY_CREATE_FAILED,
    COMMUNITY_DUPLICATE_NAME, COMMUNITY_JOIN_FAILED, COMMUNITY_LEAVE_FAILED,
    COMMUNITY_FOUNDER_LEAVE, COMMUNITY_MEMBERS_FAILED,
    COMMUNITY_CHAT_FETCH_FAILED, COMMUNITY_CHAT_SEND_FAILED,
    COMMUNITY_INVALID_INPUT,
    // Feed
    FEED_FETCH_FAILED, FEED_CREATE_FAILED, FEED_DELETE_FAILED,
    FEED_REACT_FAILED, FEED_NOT_FOUND, FEED_FORBIDDEN, FEED_INVALID_INPUT,
    // Users
    USER_NOT_FOUND, USER_UPDATE_FAILED, USER_XP_UPDATE_FAILED,
    USER_DELETE_FAILED, USER_AVATAR_FAILED, USER_INVALID_INPUT,
    USER_ROLE_UPDATE_FAILED, USER_STATS_FAILED,
    // Bugs
    BUG_INSERT_FAILED, BUG_FETCH_FAILED, BUG_UPDATE_FAILED,
    BUG_DELETE_FAILED, BUG_NOT_FOUND, BUG_INVALID_INPUT,
    // Global
    RATE_LIMITED, CORS_BLOCKED,
};
